### ISSUE TITLE
Tiada Nilai pada Tarikh Mula

### ISSUE THREAD

**Issue by arazi2021** [zaiehilmi/flutter_waktu_solat_my#1]
i'm using below sample code 

List<WaktuSolat>? senaraiWaktuSolat = await dapatkanJadualWaktuSolat(
      ZonWaktuSolat.KDH01,
      tempohJadual: TempohJadual.minggu
  );

  if (senaraiWaktuSolat != null) {
    for (var waktuSolat in senaraiWaktuSolat) {
      print('Hari ${waktuSolat.hari}: subuh ${waktuSolat.subuh}');
    }
  } else {
    print('Gagal mendapatkan senarai waktu solat.');
  }

Unhandled exception:
Ralat: tiada nilai pada "tarikhMula"
#0      dapatkanJadualWaktuSolat (package:waktu_solat_malaysia/service/esolat_api.dart:58:23)
<asynchronous suspension>
#1      main (package:waktu_solat_malaysia_api/main.dart:4:41)
<asynchronous suspension>

**Comment by zaiehilmi** [comment]
Apparently the server will be unresponsive if the range of requested `TempohJadual` included two (or more I guest) different years. This apply to `minggu` and `durasi`. I have update the package to version **1.0.3** to include the error message when this situation occurs. 

Anyway thanks for informing with this error.
