### ISSUE TITLE
Waktu Solat Not Correct

### ISSUE THREAD

**Issue by arazi2021** [zaiehilmi/flutter_waktu_solat_my#2]
Waktu Solat For WLY01 (31-12-2023)

Hari Sunday: imsak 1:56 PM  => 5:56 AM
Hari Sunday: subuh 2:06 PM => 6:06 AM

**Comment by zaiehilmi** [comment]
salam. boleh saya tahu guna tempoh jadual apa? sebab `TempohJadual.harini` je yg ok tapi bila tengok semak dia betul je😅

**Comment by arazi2021** [comment]
waalaikumsalam, 

Saya just run sample code yg di tertulis disitu. 
TQ 

Regards, 
Ahmad Razi Md Jidin 
System Consultancy Services Sdn Bhd 
36, Jalan Wangsa Delima 6, 
Pusat Bandar Wangsa Maju (KLSC), 
53300 Kuala Lumpur. 
Tel No : +603-41491919 
Fax No : +603-41492121 
Mobile No : +6012-9154019

**Comment by arazi2021** [comment]
salam 


imsak, subuh dan syurk memang lari yea timing? 

Regards, 
Ahmad Razi Md Jidin 
System Consultancy Services Sdn Bhd 
36, Jalan Wangsa Delima 6, 
Pusat Bandar Wangsa Maju (KLSC), 
53300 Kuala Lumpur. 
Tel No : +603-41491919 
Fax No : +603-41492121 
Mobile No : +6012-9154019

**Comment by zaiehilmi** [comment]
ok je ni sama? ke ada yang saya tak perasan?
![Tangkapan Skrin 2024-01-02 pada 15 41 48](https://github.com/zaiehilmi/flutter_waktu_solat_my/assets/57740351/9dc4508a-9f2e-4939-b3a3-2cf11eb10ea6)

**Comment by arazi2021** [comment]
> ok je ni sama? ke ada yang saya tak perasan? ![Tangkapan Skrin 2024-01-02 pada 15 41 48](https://private-user-images.githubusercontent.com/57740351/293646186-9dc4508a-9f2e-4939-b3a3-2cf11eb10ea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODI4NjcsIm5iZiI6MTcwNDE4MjU2NywicGF0aCI6Ii81Nzc0MDM1MS8yOTM2NDYxODYtOWRjNDUwOGEtOWYyZS00OTM5LWIzYTMtMmNmMTFlYjEwZWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA4MDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMjg2MTk3NWViNmRmNDc5NDYzNzUzZDU1NDY0ZjI0MzM5MjAyYzg3YTkzNjAwMjVkZTkzYWVjNjczYWJmZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vn8H4XgBXXdVyOw2wQM85KtPI-QEqmpBpgXE2n4voZE)

OK noted..

**Comment by zaiehilmi** [comment]
so takde masalah lah kan? kalau tak keberatan boleh share apa masalah di pihak tuan?

**Comment by arazi2021** [comment]
> so takde masalah lah kan? kalau tak keberatan boleh share apa masalah di pihak tuan?

yup...may be di code saya... TQ yea
